theme: jekyll-theme-minimal
title: [Cully Richard]
description: [Cully Richard's Porfolio for all engineering and projects related. Links to other sites and project descriptions are also here]
logo: https://github.com/cullyrichard/cullyrichard/blob/gh-pages/IMG_0313.JPG
